[package]
name = "script"
version = "0.1.0"
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rhai = "1.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rhai = { version = "1.7", features = ["wasm-bindgen"] }
